### ISSUE TITLE
redo_lci and redi_lcia fail if not supplied a demand argument

### ISSUE THREAD

**Issue by aleksandra-kim** [brightway-lca/brightway2-calc#26]
**[Original report](https://bitbucket.org/cmutel/brightway2-calc/issue/26) by Pascal Lesage (Bitbucket: [_MPa_](https://bitbucket.org/_MPa_), ).**

----------------------------------------

Despite apparently accepting `demand=None`, `LCA.redo_lci()` and `LCA.redo_lcia()` will fail if no demand argument is provided.

```python
>>> import brightway2 as bw
>>> lca = bw.LCA({('some', 'act'):1})
>>> lca.lci()
>>> lca.redo_lci()

Traceback (most recent call last):
  File "C:\mypy\anaconda\envs\bw2020\lib\site-packages\IPython\core\interactiveshell.py", line 3331, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-25-82c6d21a2d04>", line 1, in <module>
    lca.redo_lci()
  File "C:\mypy\anaconda\envs\bw2020\lib\site-packages\bw2calc\lca.py", line 516, in redo_lci
    self.logger.info("Redoing LCI", extra={'demand': wrap_functional_unit(demand or self.demand)})
  File "C:\mypy\anaconda\envs\bw2020\lib\site-packages\bw2calc\utils.py", line 219, in wrap_functional_unit
    for key, amount in dct.items():
AttributeError: 'NoneType' object has no attribute 'items'
```

The problem is [here \(](https://bitbucket.org/cmutel/brightway2-calc/src/e4441605dab2d1dd72b270e36ff2fa5190e6b920/bw2calc/lca.py#lines-515)\): and [here. ](https://bitbucket.org/cmutel/brightway2-calc/src/e4441605dab2d1dd72b270e36ff2fa5190e6b920/bw2calc/lca.py#lines-531) The line `self.demand = demand` should be in the if block.

I will provide a PR if there is no objection.

**Comment by aleksandra-kim** [comment]
**Original comment by Chris Mutel (Bitbucket: [cmutel](https://bitbucket.org/cmutel), GitHub: [cmutel](https://github.com/cmutel)).**

----------------------------------------

Fixed in [64cfb0d](https://bitbucket.org/cmutel/brightway2-calc/commits/64cfb0df849b).

‌
