### ISSUE TITLE
Unhelpful error when specifying incorrect functional unit

### ISSUE THREAD

**Issue by aleksandra-kim** [brightway-lca/brightway2-calc#9]
**[Original report](https://bitbucket.org/cmutel/brightway2-calc/issue/9) by Chris Mutel (Bitbucket: [cmutel](https://bitbucket.org/cmutel), GitHub: [cmutel](https://github.com/cmutel)).**

----------------------------------------

If you have a database 'foo', and accidentally set up an LCA with LCA({Database("bar").random(): 1}), you get the following error:

```
#!python

>>> mc = MonteCarloLCA({Database("ecoinvent 3.2 cutoff").random(): 1}, methods.random())
Warning: This database is empty
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/jupyter/libs/python-3.5.1/lib/python3.5/site-packages/bw2calc/monte_carlo.py", line 21, in __init__
    **kwargs)
  File "/home/jupyter/libs/python-3.5.1/lib/python3.5/site-packages/bw2calc/lca.py", line 66, in __init__
    self.get_array_filepaths()
  File "/home/jupyter/libs/python-3.5.1/lib/python3.5/site-packages/bw2calc/lca.py", line 71, in get_array_filepaths
    get_database_filepaths(self.demand, self._databases),
  File "/home/jupyter/libs/python-3.5.1/lib/python3.5/site-packages/bw2calc/utils.py", line 64, in get_database_filepaths
    dbs = set.union(*[Database(key[0]).find_graph_dependents() for key in functional_unit])
  File "/home/jupyter/libs/python-3.5.1/lib/python3.5/site-packages/bw2calc/utils.py", line 64, in <listcomp>
    dbs = set.union(*[Database(key[0]).find_graph_dependents() for key in functional_unit])
TypeError: 'NoneType' object is not subscriptable
```

This does nothing to help you understand what the problem actually was.

**Comment by aleksandra-kim** [comment]
**Original comment by Chris Mutel (Bitbucket: [cmutel](https://bitbucket.org/cmutel), GitHub: [cmutel](https://github.com/cmutel)).**

----------------------------------------

Give better errors with invalid demand. Fixes #9.
